services:
  opt-mult:
    build:
      context: ../../..
      dockerfile: projects/Vision.OPT_MULT/.devcontainer/Dockerfile
    image: opt-mult:latest
    container_name: opt_mult
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8051:8051"
    ipc: host
    runtime: nvidia  # Explicitly specify the nvidia runtime
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]